namespace Epica.Web.Operacion.Models.Entities
{
    public class Pais
    {
        public int Value { get; set; }
        public string Text { get; set; }
    }

    public class ApoderadoLegal
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
    }

    public static class ApoderadoLegalOpciones
    {
        public static List<ApoderadoLegal> Opciones = new List<ApoderadoLegal>
        {
            new ApoderadoLegal {Id = 1, Descripcion = "Si"},
            new ApoderadoLegal {Id = 0, Descripcion = "No"}
        };
    }

    public static class Paises
    {
        public static List<Pais> ListaDePaises = new List<Pais>
    {
        new Pais { Value = 1, Text = "AFGANISTÁN" },
        new Pais { Value = 2, Text = "ALBANIA" },
        new Pais { Value = 3, Text = "ALEMANIA" },
        new Pais { Value = 4, Text = "ANDORRA" },
        new Pais { Value = 5, Text = "ANGOLA" },
        new Pais { Value = 6, Text = "ANTIGUA Y BARBUDA" },
        new Pais { Value = 7, Text = "ARABIA SAUDITA" },
        new Pais { Value = 8, Text = "ARGELIA" },
        new Pais { Value = 9, Text = "ARGENTINA" },
        new Pais { Value = 10, Text = "ARMENIA" },
        new Pais { Value = 11, Text = "AUSTRALIA" },
        new Pais { Value = 12, Text = "AUSTRIA" },
        new Pais { Value = 13, Text = "AZERBAIYÁN" },
        new Pais { Value = 14, Text = "BAHAMAS" },
        new Pais { Value = 15, Text = "BANGLADÉS" },
        new Pais { Value = 16, Text = "BARBADOS" },
        new Pais { Value = 17, Text = "BARÉIN" },
        new Pais { Value = 18, Text = "BÉLGICA" },
        new Pais { Value = 19, Text = "BELICE" },
        new Pais { Value = 20, Text = "BENÍN" },
        new Pais { Value = 21, Text = "BIELORRUSIA" },
        new Pais { Value = 22, Text = "BIRMANIA" },
        new Pais { Value = 23, Text = "BOLIVIA" },
        new Pais { Value = 24, Text = "BOSNIA Y HERZEGOVINA" },
        new Pais { Value = 25, Text = "BOTSUANA" },
        new Pais { Value = 26, Text = "BRASIL" },
        new Pais { Value = 27, Text = "BRUNÉI" },
        new Pais { Value = 28, Text = "BULGARIA" },
        new Pais { Value = 29, Text = "BURKINA FASO" },
        new Pais { Value = 30, Text = "BURUNDI" },
        new Pais { Value = 31, Text = "BUTÁN" },
        new Pais { Value = 32, Text = "CABO VERDE" },
        new Pais { Value = 33, Text = "CAMBOYA" },
        new Pais { Value = 34, Text = "CAMERÚN" },
        new Pais { Value = 35, Text = "CANADÁ" },
        new Pais { Value = 36, Text = "CATAR" },
        new Pais { Value = 37, Text = "CHAD" },
        new Pais { Value = 38, Text = "CHILE" },
        new Pais { Value = 39, Text = "CHINA" },
        new Pais { Value = 40, Text = "CHIPRE" },
        new Pais { Value = 41, Text = "CIUDAD DEL VATICANO" },
        new Pais { Value = 42, Text = "COLOMBIA" },
        new Pais { Value = 43, Text = "COMORAS" },
        new Pais { Value = 44, Text = "COREA DEL NORTE" },
        new Pais { Value = 45, Text = "COREA DEL SUR" },
        new Pais { Value = 46, Text = "COSTA DE MARFIL" },
        new Pais { Value = 47, Text = "COSTA RICA" },
        new Pais { Value = 48, Text = "CROACIA" },
        new Pais { Value = 49, Text = "CUBA" },
        new Pais { Value = 50, Text = "DINAMARCA" },
        new Pais { Value = 51, Text = "DOMINICA" },
        new Pais { Value = 52, Text = "ECUADOR" },
        new Pais { Value = 53, Text = "EGIPTO" },
        new Pais { Value = 54, Text = "EL SALVADOR" },
        new Pais { Value = 55, Text = "EMIRATOS ÁRABES UNIDOS" },
        new Pais { Value = 56, Text = "ERITREA" },
        new Pais { Value = 57, Text = "ESLOVAQUIA" },
        new Pais { Value = 58, Text = "ESLOVENIA" },
        new Pais { Value = 59, Text = "ESPAÑA" },
        new Pais { Value = 60, Text = "ESTADOS UNIDOS" },
        new Pais { Value = 61, Text = "ESTONIA" },
        new Pais { Value = 62, Text = "ETIOPÍA" },
        new Pais { Value = 63, Text = "FILIPINAS" },
        new Pais { Value = 64, Text = "FINLANDIA" },
        new Pais { Value = 65, Text = "FIYI" },
        new Pais { Value = 66, Text = "FRANCIA" },
        new Pais { Value = 67, Text = "GABÓN" },
        new Pais { Value = 68, Text = "GAMBIA" },
        new Pais { Value = 69, Text = "GEORGIA" },
        new Pais { Value = 70, Text = "GHANA" },
        new Pais { Value = 71, Text = "GRANADA" },
        new Pais { Value = 72, Text = "GRECIA" },
        new Pais { Value = 73, Text = "GUATEMALA" },
        new Pais { Value = 74, Text = "GUINEA ECUATORIAL" },
        new Pais { Value = 75, Text = "GUINEA" },
        new Pais { Value = 76, Text = "GUINEA-BISÁU" },
        new Pais { Value = 77, Text = "GUYANA" },
        new Pais { Value = 78, Text = "HAITÍ" },
        new Pais { Value = 79, Text = "HONDURAS" },
        new Pais { Value = 80, Text = "HUNGRÍA" },
        new Pais { Value = 81, Text = "INDIA" },
        new Pais { Value = 82, Text = "INDONESIA" },
        new Pais { Value = 83, Text = "IRAK" },
        new Pais { Value = 84, Text = "IRÁN" },
        new Pais { Value = 85, Text = "IRLANDA" },
        new Pais { Value = 86, Text = "ISLANDIA" },
        new Pais { Value = 87, Text = "ISLAS MARSHALL" },
        new Pais { Value = 88, Text = "ISLAS SALOMÓN" },
        new Pais { Value = 89, Text = "ISRAEL" },
        new Pais { Value = 90, Text = "ITALIA" },
        new Pais { Value = 91, Text = "JAMAICA" },
        new Pais { Value = 92, Text = "JAPÓN" },
        new Pais { Value = 93, Text = "JORDANIA" },
        new Pais { Value = 94, Text = "KAZAJISTÁN" },
        new Pais { Value = 95, Text = "KENIA" },
        new Pais { Value = 96, Text = "KIRGUISTÁN" },
        new Pais { Value = 97, Text = "KIRIBATI" },
        new Pais { Value = 98, Text = "KUWAIT" },
        new Pais { Value = 99, Text = "LAOS" },
        new Pais { Value = 100, Text = "LESOTO" },
        new Pais { Value = 101, Text = "LETONIA" },
        new Pais { Value = 102, Text = "LÍBANO" },
        new Pais { Value = 103, Text = "LIBERIA" },
        new Pais { Value = 104, Text = "LIBIA" },
        new Pais { Value = 105, Text = "LIECHTENSTEIN" },
        new Pais { Value = 106, Text = "LITUANIA" },
        new Pais { Value = 107, Text = "LUXEMBURGO" },
        new Pais { Value = 108, Text = "MADAGASCAR" },
        new Pais { Value = 109, Text = "MALASIA" },
        new Pais { Value = 110, Text = "MALAUI" },
        new Pais { Value = 111, Text = "MALDIVAS" },
        new Pais { Value = 112, Text = "MALÍ" },
        new Pais { Value = 113, Text = "MALTA" },
        new Pais { Value = 114, Text = "MARRUECOS" },
        new Pais { Value = 115, Text = "MAURICIO" },
        new Pais { Value = 116, Text = "MAURITANIA" },
        new Pais { Value = 117, Text = "MÉXICO" },
        new Pais { Value = 118, Text = "MICRONESIA" },
        new Pais { Value = 119, Text = "MOLDAVIA" },
        new Pais { Value = 120, Text = "MÓNACO" },
        new Pais { Value = 121, Text = "MONGOLIA" },
        new Pais { Value = 122, Text = "MONTENEGRO" },
        new Pais { Value = 123, Text = "MOZAMBIQUE" },
        new Pais { Value = 124, Text = "NAMIBIA" },
        new Pais { Value = 125, Text = "NAURU" },
        new Pais { Value = 126, Text = "NEPAL" },
        new Pais { Value = 127, Text = "NICARAGUA" },
        new Pais { Value = 128, Text = "NÍGER" },
        new Pais { Value = 129, Text = "NIGERIA" },
        new Pais { Value = 130, Text = "NORUEGA" },
        new Pais { Value = 131, Text = "NUEVA ZELANDA" },
        new Pais { Value = 132, Text = "OMÁN" },
        new Pais { Value = 133, Text = "PAÍSES BAJOS" },
        new Pais { Value = 134, Text = "PAKISTÁN" },
        new Pais { Value = 135, Text = "PALAOS" },
        new Pais { Value = 136, Text = "PANAMÁ" },
        new Pais { Value = 137, Text = "PAPÚA NUEVA GUINEA" },
        new Pais { Value = 138, Text = "PARAGUAY" },
        new Pais { Value = 139, Text = "PERÚ" },
        new Pais { Value = 140, Text = "POLONIA" },
        new Pais { Value = 141, Text = "PORTUGAL" },
        new Pais { Value = 142, Text = "REINO UNIDO" },
        new Pais { Value = 143, Text = "REPÚBLICA CENTROAFRICANA" },
        new Pais { Value = 144, Text = "REPÚBLICA CHECA" },
        new Pais { Value = 145, Text = "REPÚBLICA DE MACEDONIA" },
        new Pais { Value = 146, Text = "REPÚBLICA DEL CONGO" },
        new Pais { Value = 147, Text = "REPÚBLICA DEMOCRÁTICA DEL CONGO" },
        new Pais { Value = 148, Text = "REPÚBLICA DOMINICANA" },
        new Pais { Value = 149, Text = "REPÚBLICA SUDAFRICANA" },
        new Pais { Value = 150, Text = "RUANDA" },
        new Pais { Value = 151, Text = "RUMANÍA" },
        new Pais { Value = 152, Text = "RUSIA" },
        new Pais { Value = 153, Text = "SAMOA" },
        new Pais { Value = 154, Text = "SAN CRISTÓBAL Y NIEVES" },
        new Pais { Value = 155, Text = "SAN MARINO" },
        new Pais { Value = 156, Text = "SAN VICENTE Y LAS GRANADINAS" },
        new Pais { Value = 157, Text = "SANTA LUCÍA" },
        new Pais { Value = 158, Text = "SANTO TOMÉ Y PRÍNCIPE" },
        new Pais { Value = 159, Text = "SENEGAL" },
        new Pais { Value = 160, Text = "SERBIA" },
        new Pais { Value = 161, Text = "SEYCHELLES" },
        new Pais { Value = 162, Text = "SIERRA LEONA" },
        new Pais { Value = 163, Text = "SINGAPUR" },
        new Pais { Value = 164, Text = "SIRIA" },
        new Pais { Value = 165, Text = "SOMALIA" },
        new Pais { Value = 166, Text = "SRI LANKA" },
        new Pais { Value = 167, Text = "SUAZILANDIA" },
        new Pais { Value = 168, Text = "SUDÁN DEL SUR" },
        new Pais { Value = 169, Text = "SUDÁN" },
        new Pais { Value = 170, Text = "SUECIA" },
        new Pais { Value = 171, Text = "SUIZA" },
        new Pais { Value = 172, Text = "SURINAM" },
        new Pais { Value = 173, Text = "TAILANDIA" },
        new Pais { Value = 174, Text = "TANZANIA" },
        new Pais { Value = 175, Text = "TAYIKISTÁN" },
        new Pais { Value = 176, Text = "TIMOR ORIENTAL" },
        new Pais { Value = 177, Text = "TOGO" },
        new Pais { Value = 178, Text = "TONGA" },
        new Pais { Value = 179, Text = "TRINIDAD Y TOBAGO" },
        new Pais { Value = 180, Text = "TÚNEZ" },
        new Pais { Value = 181, Text = "TURKMENISTÁN" },
        new Pais { Value = 182, Text = "TURQUÍA" },
        new Pais { Value = 183, Text = "TUVALU" },
        new Pais { Value = 184, Text = "UCRANIA" },
        new Pais { Value = 185, Text = "UGANDA" },
        new Pais { Value = 186, Text = "URUGUAY" },
        new Pais { Value = 187, Text = "UZBEKISTÁN" },
        new Pais { Value = 188, Text = "VANUATU" },
        new Pais { Value = 189, Text = "VENEZUELA" },
        new Pais { Value = 190, Text = "VIETNAM" },
        new Pais { Value = 191, Text = "YEMEN" },
        new Pais { Value = 192, Text = "YIBUTI" },
        new Pais { Value = 193, Text = "ZAMBIA" },
        new Pais { Value = 194, Text = "ZIMBABUE" },
    };
    }
}
