namespace Epica.Web.Operacion.Models.Entities
{
    public class Pais
    {
        public int Value { get; set; }
        public string Text { get; set; }
    }

    public class ApoderadoLegal
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
    }

    public static class ApoderadoLegalOpciones
    {
        public static List<ApoderadoLegal> Opciones = new List<ApoderadoLegal>
        {
            new ApoderadoLegal {Id = 1, Descripcion = "Si"},
            new ApoderadoLegal {Id = 0, Descripcion = "No"}
        };
    }

    public static class Paises
    {
        public static List<Pais> ListaDePaises = new List<Pais>
        {
            new Pais { Value = 1, Text = "Afganistán" },
            new Pais { Value = 2, Text = "Albania" },
            new Pais { Value = 3, Text = "Alemania" },
            new Pais { Value = 4, Text = "Andorra" },
            new Pais { Value = 5, Text = "Angola" },
            new Pais { Value = 6, Text = "Antigua y Barbuda" },
            new Pais { Value = 7, Text = "Arabia Saudita" },
            new Pais { Value = 8, Text = "Argelia" },
            new Pais { Value = 9, Text = "Argentina" },
            new Pais { Value = 10, Text = "Armenia" },
            new Pais { Value = 11, Text = "Australia" },
            new Pais { Value = 12, Text = "Austria" },
            new Pais { Value = 13, Text = "Azerbaiyán" },
            new Pais { Value = 14, Text = "Bahamas" },
            new Pais { Value = 15, Text = "Bangladés" },
            new Pais { Value = 16, Text = "Barbados" },
            new Pais { Value = 17, Text = "Baréin" },
            new Pais { Value = 18, Text = "Bélgica" },
            new Pais { Value = 19, Text = "Belice" },
            new Pais { Value = 20, Text = "Benín" },
            new Pais { Value = 21, Text = "Bielorrusia" },
            new Pais { Value = 22, Text = "Birmania" },
            new Pais { Value = 23, Text = "Bolivia" },
            new Pais { Value = 24, Text = "Bosnia y Herzegovina" },
            new Pais { Value = 25, Text = "Botsuana" },
            new Pais { Value = 26, Text = "Brasil" },
            new Pais { Value = 27, Text = "Brunéi" },
            new Pais { Value = 28, Text = "Bulgaria" },
            new Pais { Value = 29, Text = "Burkina Faso" },
            new Pais { Value = 30, Text = "Burundi" },
            new Pais { Value = 31, Text = "Bután" },
            new Pais { Value = 32, Text = "Cabo Verde" },
            new Pais { Value = 33, Text = "Camboya" },
            new Pais { Value = 34, Text = "Camerún" },
            new Pais { Value = 35, Text = "Canadá" },
            new Pais { Value = 36, Text = "Catar" },
            new Pais { Value = 37, Text = "Chad" },
            new Pais { Value = 38, Text = "Chile" },
            new Pais { Value = 39, Text = "China" },
            new Pais { Value = 40, Text = "Chipre" },
            new Pais { Value = 41, Text = "Ciudad del Vaticano" },
            new Pais { Value = 42, Text = "Colombia" },
            new Pais { Value = 43, Text = "Comoras" },
            new Pais { Value = 44, Text = "Corea del Norte" },
            new Pais { Value = 45, Text = "Corea del Sur" },
            new Pais { Value = 46, Text = "Costa de Marfil" },
            new Pais { Value = 47, Text = "Costa Rica" },
            new Pais { Value = 48, Text = "Croacia" },
            new Pais { Value = 49, Text = "Cuba" },
            new Pais { Value = 50, Text = "Dinamarca" },
            new Pais { Value = 51, Text = "Dominica" },
            new Pais { Value = 52, Text = "Ecuador" },
            new Pais { Value = 53, Text = "Egipto" },
            new Pais { Value = 54, Text = "El Salvador" },
            new Pais { Value = 55, Text = "Emiratos Árabes Unidos" },
            new Pais { Value = 56, Text = "Eritrea" },
            new Pais { Value = 57, Text = "Eslovaquia" },
            new Pais { Value = 58, Text = "Eslovenia" },
            new Pais { Value = 59, Text = "España" },
            new Pais { Value = 60, Text = "Estados Unidos" },
            new Pais { Value = 61, Text = "Estonia" },
            new Pais { Value = 62, Text = "Etiopía" },
            new Pais { Value = 63, Text = "Filipinas" },
            new Pais { Value = 64, Text = "Finlandia" },
            new Pais { Value = 65, Text = "Fiyi" },
            new Pais { Value = 66, Text = "Francia" },
            new Pais { Value = 67, Text = "Gabón" },
            new Pais { Value = 68, Text = "Gambia" },
            new Pais { Value = 69, Text = "Georgia" },
            new Pais { Value = 70, Text = "Ghana" },
            new Pais { Value = 71, Text = "Granada" },
            new Pais { Value = 72, Text = "Grecia" },
            new Pais { Value = 73, Text = "Guatemala" },
            new Pais { Value = 74, Text = "Guinea Ecuatorial" },
            new Pais { Value = 75, Text = "Guinea" },
            new Pais { Value = 76, Text = "Guinea-Bisáu" },
            new Pais { Value = 77, Text = "Guyana" },
            new Pais { Value = 78, Text = "Haití" },
            new Pais { Value = 79, Text = "Honduras" },
            new Pais { Value = 80, Text = "Hungría" },
            new Pais { Value = 81, Text = "India" },
            new Pais { Value = 82, Text = "Indonesia" },
            new Pais { Value = 83, Text = "Irak" },
            new Pais { Value = 84, Text = "Irán" },
            new Pais { Value = 85, Text = "Irlanda" },
            new Pais { Value = 86, Text = "Islandia" },
            new Pais { Value = 87, Text = "Islas Marshall" },
            new Pais { Value = 88, Text = "Islas Salomón" },
            new Pais { Value = 89, Text = "Israel" },
            new Pais { Value = 90, Text = "Italia" },
            new Pais { Value = 91, Text = "Jamaica" },
            new Pais { Value = 92, Text = "Japón" },
            new Pais { Value = 93, Text = "Jordania" },
            new Pais { Value = 94, Text = "Kazajistán" },
            new Pais { Value = 95, Text = "Kenia" },
            new Pais { Value = 96, Text = "Kirguistán" },
            new Pais { Value = 97, Text = "Kiribati" },
            new Pais { Value = 98, Text = "Kuwait" },
            new Pais { Value = 99, Text = "Laos" },
            new Pais { Value = 100, Text = "Lesoto" },
            new Pais { Value = 101, Text = "Letonia" },
            new Pais { Value = 102, Text = "Líbano" },
            new Pais { Value = 103, Text = "Liberia" },
            new Pais { Value = 104, Text = "Libia" },
            new Pais { Value = 105, Text = "Liechtenstein" },
            new Pais { Value = 106, Text = "Lituania" },
            new Pais { Value = 107, Text = "Luxemburgo" },
            new Pais { Value = 108, Text = "Madagascar" },
            new Pais { Value = 109, Text = "Malasia" },
            new Pais { Value = 110, Text = "Malaui" },
            new Pais { Value = 111, Text = "Maldivas" },
            new Pais { Value = 112, Text = "Malí" },
            new Pais { Value = 113, Text = "Malta" },
            new Pais { Value = 114, Text = "Marruecos" },
            new Pais { Value = 115, Text = "Mauricio" },
            new Pais { Value = 116, Text = "Mauritania" },
            new Pais { Value = 117, Text = "México" },
            new Pais { Value = 118, Text = "Micronesia" },
            new Pais { Value = 119, Text = "Moldavia" },
            new Pais { Value = 120, Text = "Mónaco" },
            new Pais { Value = 121, Text = "Mongolia" },
            new Pais { Value = 122, Text = "Montenegro" },
            new Pais { Value = 123, Text = "Mozambique" },
            new Pais { Value = 124, Text = "Namibia" },
            new Pais { Value = 125, Text = "Nauru" },
            new Pais { Value = 126, Text = "Nepal" },
            new Pais { Value = 127, Text = "Nicaragua" },
            new Pais { Value = 128, Text = "Níger" },
            new Pais { Value = 129, Text = "Nigeria" },
            new Pais { Value = 130, Text = "Noruega" },
            new Pais { Value = 131, Text = "Nueva Zelanda" },
            new Pais { Value = 132, Text = "Omán" },
            new Pais { Value = 133, Text = "Países Bajos" },
            new Pais { Value = 134, Text = "Pakistán" },
            new Pais { Value = 135, Text = "Palaos" },
            new Pais { Value = 136, Text = "Panamá" },
            new Pais { Value = 137, Text = "Papúa Nueva Guinea" },
            new Pais { Value = 138, Text = "Paraguay" },
            new Pais { Value = 139, Text = "Perú" },
            new Pais { Value = 140, Text = "Polonia" },
            new Pais { Value = 141, Text = "Portugal" },
            new Pais { Value = 142, Text = "Reino Unido" },
            new Pais { Value = 143, Text = "República Centroafricana" },
            new Pais { Value = 144, Text = "República Checa" },
            new Pais { Value = 145, Text = "República de Macedonia" },
            new Pais { Value = 146, Text = "República del Congo" },
            new Pais { Value = 147, Text = "República Democrática del Congo" },
            new Pais { Value = 148, Text = "República Dominicana" },
            new Pais { Value = 149, Text = "República Sudafricana" },
            new Pais { Value = 150, Text = "Ruanda" },
            new Pais { Value = 151, Text = "Rumanía" },
            new Pais { Value = 152, Text = "Rusia" },
            new Pais { Value = 153, Text = "Samoa" },
            new Pais { Value = 154, Text = "San Cristóbal y Nieves" },
            new Pais { Value = 155, Text = "San Marino" },
            new Pais { Value = 156, Text = "San Vicente y las Granadinas" },
            new Pais { Value = 157, Text = "Santa Lucía" },
            new Pais { Value = 158, Text = "Santo Tomé y Príncipe" },
            new Pais { Value = 159, Text = "Senegal" },
            new Pais { Value = 160, Text = "Serbia" },
            new Pais { Value = 161, Text = "Seychelles" },
            new Pais { Value = 162, Text = "Sierra Leona" },
            new Pais { Value = 163, Text = "Singapur" },
            new Pais { Value = 164, Text = "Siria" },
            new Pais { Value = 165, Text = "Somalia" },
            new Pais { Value = 166, Text = "Sri Lanka" },
            new Pais { Value = 167, Text = "Suazilandia" },
            new Pais { Value = 168, Text = "Sudán del Sur" },
            new Pais { Value = 169, Text = "Sudán" },
            new Pais { Value = 170, Text = "Suecia" },
            new Pais { Value = 171, Text = "Suiza" },
            new Pais { Value = 172, Text = "Surinam" },
            new Pais { Value = 173, Text = "Tailandia" },
            new Pais { Value = 174, Text = "Tanzania" },
            new Pais { Value = 175, Text = "Tayikistán" },
            new Pais { Value = 176, Text = "Timor Oriental" },
            new Pais { Value = 177, Text = "Togo" },
            new Pais { Value = 178, Text = "Tonga" },
            new Pais { Value = 179, Text = "Trinidad y Tobago" },
            new Pais { Value = 180, Text = "Túnez" },
            new Pais { Value = 181, Text = "Turkmenistán" },
            new Pais { Value = 182, Text = "Turquía" },
            new Pais { Value = 183, Text = "Tuvalu" },
            new Pais { Value = 184, Text = "Ucrania" },
            new Pais { Value = 185, Text = "Uganda" },
            new Pais { Value = 186, Text = "Uruguay" },
            new Pais { Value = 187, Text = "Uzbekistán" },
            new Pais { Value = 188, Text = "Vanuatu" },
            new Pais { Value = 189, Text = "Venezuela" },
            new Pais { Value = 190, Text = "Vietnam" },
            new Pais { Value = 191, Text = "Yemen" },
            new Pais { Value = 192, Text = "Yibuti" },
            new Pais { Value = 193, Text = "Zambia" },
            new Pais { Value = 194, Text = "Zimbabue" },
        };
    }
}
